repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: forbid-new-submodules
    -   id: check-added-large-files
        args: ['--maxkb=150']
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-toml
    -   id: detect-private-key
-   repo: https://github.com/Vimjas/vint
    rev: db881f8 
    hooks:
    -   id: vint
